apiVersion: v1
kind: Secret
metadata:
  name: soundsentinel-app-secrets
  namespace: soundsentinel
type: Opaque
stringData:
  SOUNDSENTINEL_POSTGRES_USER: "soundsentinel"
  SOUNDSENTINEL_POSTGRES_PASSWORD: "change-me"
  SOUNDSENTINEL_TELEGRAM_BOT_TOKEN: ""
  SOUNDSENTINEL_TELEGRAM_CHAT_ID: ""
  SOUNDSENTINEL_SENSOR_ADMIN_TOKEN: ""
