apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: soundsentinel
  namespace: soundsentinel
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
spec:
  rules:
    - host: soundsentinel.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: soundsentinel-app
                port:
                  number: 80

