apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: soundsentinel-postgres-pvc
  namespace: soundsentinel
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

