apiVersion: v1
kind: Secret
metadata:
  name: soundsentinel-postgres-secrets
  namespace: soundsentinel
type: Opaque
stringData:
  POSTGRES_USER: "soundsentinel"
  POSTGRES_PASSWORD: "change-me"
  POSTGRES_DB: "soundsentinel"

